# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 大钻风的博客
email: dazuanfeng@qq.com
description: > # this means to ignore newlines until "baseurl:"
  服务端笔记一箩筐
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dazuanfeng.github.io" # the base hostname & protocol for your site
weibo_username: http://weibo.com/zhangzhuanfeng
github_username:  yiyiboy2010

# Build settings
markdown: kramdown
